language: java

before_install:
  - echo "MAVEN_OPTS='-server -Xms512m -Xmx1024m -Xss16m'" > ~/.mavenrc
install: true
script:
  - mvn clean verify

cache:
 directories:
   - $HOME/.m2

jdk:
  - oraclejdk8
